---
  php::ensure: latest
  php::manage_repos: true
  php::fpm: true
  php::dev: true
  php::composer: true
  php::pear: true
  php::phpunit: true
  php::settings:
    'PHP/max_execution_time': '90'
    'PHP/max_input_time': '300'
    'PHP/memory_limit': '64M'
    'PHP/post_max_size': '32M'
    'PHP/upload_max_filesize': '32M'
    'Date/date.timezone': 'Europe/London'
  php::extensions:
    mysql: {}
  nginx::nginx_vhosts:
    'localhost':
      www_root: '/var/share'
  nginx::nginx_locations:
    'static':
      location: '~ "\.php$"'
      vhost: localhost
      www_root: /var/share
      fastcgi: '127.0.0.1:9000'
